import Head from "next/head";

import { z } from "zod";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import "picnic/picnic.min.css";

import styles from "@/styles/Home.module.css";

const schema = z.object({
  tanggalPembuatan: z.string().min(1),
  jadwalReguler: z.string().min(1),
  waktuReguler: z.string().min(1),
});
type FormValues = z.infer<typeof schema>;

export default function Home() {
  const { register, handleSubmit } = useForm<FormValues>({
    resolver: zodResolver(schema),
  });

  useEffect(() => {
    console.log("tes");
  }, []);

  return (
    <>
      <Head>
        <title>Pembuatan Surat AKOM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div>
          <form onSubmit={handleSubmit((d) => console.log(d))}>
            <fieldset className={styles.group}>
              <label>Tanggal Pembuatan Dokumen</label>
              <input
                className={styles.input}
                placeholder="Masukan Tanggal Pembuatan File"
                {...register("tanggalPembuatan")}
              />
            </fieldset>

            <fieldset className={styles.group}>
              <label>Jadwal Reguler</label>
              <input
                className={styles.input}
                placeholder="Masukan Jadwal Reguler"
                {...register("jadwalReguler")}
              />
            </fieldset>

            <fieldset className={styles.group}>
              <label>Waktu Reguler</label>
              <input
                className={styles.input}
                placeholder="Masukan Waktu Reguler"
                {...register("waktuReguler")}
              />
            </fieldset>

            <button className={styles.button} type="submit">
              Cetak
            </button>
          </form>
        </div>
      </main>
    </>
  );
}
