import Head from "next/head";
import { DateTime } from "luxon";
import { useEffect } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm, useFieldArray } from "react-hook-form";

import type { GetServerSideProps } from "next";
import { env } from "@/env/client.mjs";

import "picnic/picnic.min.css";

import styles from "@/styles/Home.module.css";

import { schema, type FormValues } from "@/schemas/home.schema";

interface IProps {
  cookies: { [key: string]: string };
}

export default function Home({ cookies }: IProps) {
  const { control, register, setValue, handleSubmit } = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      kelas: [{ value: "XII IPA 4" }],
    },
  });
  const { fields, append, remove } = useFieldArray({
    name: "kelas",
    control,
  });

  useEffect(() => {
    const now = DateTime.now().setLocale("id");
    const isNextWeek = now.weekday >= 3;

    const nextSchedule = isNextWeek
      ? now.startOf("week").plus({ week: 1, day: 2 })
      : now.plus({ day: 3 - now.weekday });

    setValue(
      "tanggalPembuatan",
      `Bekasi, ${now.toLocaleString(DateTime.DATE_FULL)}`
    );
    setValue("jadwalReguler", nextSchedule.toLocaleString(DateTime.DATE_FULL));
    setValue("waktuReguler", "16.10 - selesai");

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const onSubmit = async (pdfInfo: FormValues) => {
    const blob = await fetch(
      `${env.NEXT_PUBLIC_FUNCTION_ENDPOINT}/.netlify/functions/gen-pdf`,
      {
        method: "POST",
        body: JSON.stringify({
          pdfInfo,
          userInfo: cookies,
        }),
      }
    ).then((res) => res.blob());

    console.log(URL.createObjectURL(blob));
  };

  return (
    <>
      <Head>
        <title>Pembuatan Surat AKOM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div>
          <form onSubmit={handleSubmit(onSubmit)}>
            <fieldset className={styles.group}>
              <label>Surat Ke</label>
              <input
                className={styles.input}
                placeholder="Urutan surat ke"
                {...register("suratKe")}
              />
            </fieldset>

            <fieldset className={styles.group}>
              <label>Tanggal Pembuatan Dokumen</label>
              <input
                className={styles.input}
                placeholder="Tempat, Tanggal Bulan Tahun"
                {...register("tanggalPembuatan")}
              />
            </fieldset>

            <fieldset className={styles.group}>
              <label>Jadwal Reguler</label>
              <input
                className={styles.input}
                placeholder="Tanggal Bulan Tahun"
                {...register("jadwalReguler")}
              />
            </fieldset>

            <fieldset className={styles.group}>
              <label>Waktu Reguler</label>
              <input
                className={styles.input}
                placeholder="Masukan Waktu Reguler"
                {...register("waktuReguler")}
              />
            </fieldset>

            <fieldset className={styles.group}>
              <label>Kelas Yang Dipakai</label>
              {fields.map((field, index) => (
                <div
                  key={field.id}
                  style={{
                    display: "inline-flex",
                    width: "100%",
                    gap: "0.3em",
                  }}
                >
                  <button onClick={() => append({ value: "" })}>Tambah</button>
                  {index > 0 ? (
                    <button className="error" onClick={() => remove(index)}>
                      Hapus
                    </button>
                  ) : null}
                  <input
                    style={{ width: "100%" }}
                    className={styles.input}
                    placeholder="Masukan Kelas reguler"
                    {...register(`kelas.${index}.value` as const)}
                  />
                </div>
              ))}
            </fieldset>

            <button className={styles.button} type="submit">
              Cetak
            </button>
          </form>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      cookies: context.req.cookies,
    },
  };
};
