import qs from "qs";
import Head from "next/head";
import { DateTime } from "luxon";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import "picnic/picnic.min.css";

import styles from "@/styles/Home.module.css";

import { schema, type FormValues } from "@/schemas/home.schema";

export default function Home() {
  const router = useRouter();

  const { register, setValue, handleSubmit } = useForm<FormValues>({
    resolver: zodResolver(schema),
  });

  useEffect(() => {
    const now = DateTime.now().setLocale("id");

    console.log(now);

    setValue(
      "tanggalPembuatan",
      `Bekasi, ${now.toLocaleString(DateTime.DATE_FULL)}`
    );
    setValue("waktuReguler", "16.10 - selesai");
  }, []);

  const onSubmit = (data: FormValues) => {
    const path = `/print?${qs.stringify(data)}`;

    router.push(path);
  };

  return (
    <>
      <Head>
        <title>Pembuatan Surat AKOM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div>
          <form onSubmit={handleSubmit(onSubmit)}>
            <fieldset className={styles.group}>
              <label>Tanggal Pembuatan Dokumen</label>
              <input
                className={styles.input}
                placeholder="Tempat, Tanggal Bulan Tahun"
                {...register("tanggalPembuatan")}
              />
            </fieldset>

            <fieldset className={styles.group}>
              <label>Jadwal Reguler</label>
              <input
                className={styles.input}
                placeholder="Tanggal Bulan Tahun"
                {...register("jadwalReguler")}
              />
            </fieldset>

            <fieldset className={styles.group}>
              <label>Waktu Reguler</label>
              <input
                className={styles.input}
                placeholder="Masukan Waktu Reguler"
                {...register("waktuReguler")}
              />
            </fieldset>

            <button className={styles.button} type="submit">
              Cetak
            </button>
          </form>
        </div>
      </main>
    </>
  );
}
